In [1]:
import numpy as np 

In [2]:
arr=np.array([1,2,3,4,5])  #array 
arr

array([1, 2, 3, 4, 5])

In [3]:
arr2=np.array([[1,2,3],[4,3,2]])  #ndimentional array
arr2

array([[1, 2, 3],
       [4, 3, 2]])

In [4]:
arr3=np.array([[1,2,3],[2,3,4],[7,5,4]])
arr3.ndim  #ndim find the dimention of array

2

In [5]:
#find the size of each data item 
arr3.itemsize,"bytes"


(4, 'bytes')

In [6]:
#shape and size of array
arr3.size

9

In [7]:
arr3.shape

(3, 3)

In [8]:
#reshaping the array object 
arr3.reshape(9,1)

array([[1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [7],
       [5],
       [4]])

In [9]:
#slicing in array
arr3[0,1]
arr3[1,2]

4

In [10]:
#linspace evenly space 
a=np.linspace(2,4,5)
a

array([2. , 2.5, 3. , 3.5, 4. ])

In [11]:
#max min sum 
a=np.array([22,3,4,5,6,7,99,8])
a.max()
a.min()
a.sum()

154

In [12]:
#numpy array axis, axis 1 = rows, axis 0 = columns
arr3

array([[1, 2, 3],
       [2, 3, 4],
       [7, 5, 4]])

In [13]:
arr3.max(axis=0) 
arr3.max(axis=1)
arr3.min(axis=0)
arr3.min(axis=1)

array([1, 2, 4])

In [14]:
#square root standard deviation
np.sqrt(arr3)
np.std(arr3)

1.7069212773041353

In [15]:
#arithmetic operations
# + -*/


In [16]:
#array concatination/ arrange or link 
a = np.array([[1,2,344],[10,15,4]])  
b = np.array([[1,2,32],[12, 19, 29]]) 
np.vstack((a,b)) #vertically 
np.hstack((a,b))  # horizontally 


array([[  1,   2, 344,   1,   2,  32],
       [ 10,  15,   4,  12,  19,  29]])

In [17]:
#empty array 
arr=np.empty((3,2),dtype=int)
arr

array([[ 627415760,        415],
       [ 627415856,        415],
       [1946640134, 2080406536]])

In [18]:
#zero array 
arr=np.zeros((3,2),dtype=int)
arr

array([[0, 0],
       [0, 0],
       [0, 0]])

In [19]:
#ones 
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
#creat np array using list /tuple /more than one list 
i=[1,2,3,4,5,6]
np.asarray(i)
type(a)

numpy.ndarray

In [21]:
# iterable one dimention
i=[1,2,3,4,5,6]
it=iter(i)
x=np.fromiter(it,dtype=float)
x

array([1., 2., 3., 4., 5., 6.])

In [22]:
#range 
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [23]:
#separated values /separet /part
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [24]:
#end false 
np.linspace(10,20,5,endpoint=False)

array([10., 12., 14., 16., 18.])

In [25]:
#seperate on log scale
np.logspace(10,20,num=5,endpoint=True)

array([1.00000000e+10, 3.16227766e+12, 1.00000000e+15, 3.16227766e+17,
       1.00000000e+20])

In [26]:
#iteration 
a=np.array([[1,2,3],[33,22,11],[5,6,7]])

for i in np.nditer(a):
    print(i,end=" ")

1 2 3 33 22 11 5 6 7 

In [27]:
#transpose changing rows to columns
ar=np.array([[1,2,3,4],[5,6,7,8],[9,33,44,55]])
br=a.T
br

array([[ 1, 33,  5],
       [ 2, 22,  6],
       [ 3, 11,  7]])

In [42]:
#strung operations 
np.char.multiply("hello",4)
np.char.add(['wellcome ','hello '],['to the numpy','how are youu hahha'])
print(np.char.split('hello chanel welcome to my guys'),sep= "")

['hello', 'chanel', 'welcome', 'to', 'my', 'guys']


In [48]:
#sorting 
a=np.array([[1,49,2],[99,44,35]])
a
np.sort(a)
np.sort(a,0)
np.sort(a,1)

array([[ 1,  2, 49],
       [35, 44, 99]])